// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: protobuf/market.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FoodItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Calories      int32                  `protobuf:"varint,3,opt,name=calories,proto3" json:"calories,omitempty"`
	Sugar         float32                `protobuf:"fixed32,4,opt,name=sugar,proto3" json:"sugar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodItem) Reset() {
	*x = FoodItem{}
	mi := &file_protobuf_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodItem) ProtoMessage() {}

func (x *FoodItem) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodItem.ProtoReflect.Descriptor instead.
func (*FoodItem) Descriptor() ([]byte, []int) {
	return file_protobuf_market_proto_rawDescGZIP(), []int{0}
}

func (x *FoodItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FoodItem) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *FoodItem) GetCalories() int32 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *FoodItem) GetSugar() float32 {
	if x != nil {
		return x.Sugar
	}
	return 0
}

type ListAllFoodItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllFoodItemsRequest) Reset() {
	*x = ListAllFoodItemsRequest{}
	mi := &file_protobuf_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllFoodItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllFoodItemsRequest) ProtoMessage() {}

func (x *ListAllFoodItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllFoodItemsRequest.ProtoReflect.Descriptor instead.
func (*ListAllFoodItemsRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_market_proto_rawDescGZIP(), []int{1}
}

type ListAllFoodItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FoodItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllFoodItemsResponse) Reset() {
	*x = ListAllFoodItemsResponse{}
	mi := &file_protobuf_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllFoodItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllFoodItemsResponse) ProtoMessage() {}

func (x *ListAllFoodItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllFoodItemsResponse.ProtoReflect.Descriptor instead.
func (*ListAllFoodItemsResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_market_proto_rawDescGZIP(), []int{2}
}

func (x *ListAllFoodItemsResponse) GetItems() []*FoodItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListFoodItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoodItemRequest) Reset() {
	*x = ListFoodItemRequest{}
	mi := &file_protobuf_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoodItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoodItemRequest) ProtoMessage() {}

func (x *ListFoodItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoodItemRequest.ProtoReflect.Descriptor instead.
func (*ListFoodItemRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_market_proto_rawDescGZIP(), []int{3}
}

func (x *ListFoodItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListFoodItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *FoodItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoodItemResponse) Reset() {
	*x = ListFoodItemResponse{}
	mi := &file_protobuf_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoodItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoodItemResponse) ProtoMessage() {}

func (x *ListFoodItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoodItemResponse.ProtoReflect.Descriptor instead.
func (*ListFoodItemResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_market_proto_rawDescGZIP(), []int{4}
}

func (x *ListFoodItemResponse) GetItem() *FoodItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateFoodItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Item          *FoodItem              `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFoodItemRequest) Reset() {
	*x = UpdateFoodItemRequest{}
	mi := &file_protobuf_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFoodItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFoodItemRequest) ProtoMessage() {}

func (x *UpdateFoodItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFoodItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateFoodItemRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_market_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFoodItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFoodItemRequest) GetItem() *FoodItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateFoodItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFoodItemResponse) Reset() {
	*x = UpdateFoodItemResponse{}
	mi := &file_protobuf_market_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFoodItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFoodItemResponse) ProtoMessage() {}

func (x *UpdateFoodItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_market_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFoodItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateFoodItemResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_market_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateFoodItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddFoodItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *FoodItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFoodItemRequest) Reset() {
	*x = AddFoodItemRequest{}
	mi := &file_protobuf_market_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFoodItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFoodItemRequest) ProtoMessage() {}

func (x *AddFoodItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_market_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFoodItemRequest.ProtoReflect.Descriptor instead.
func (*AddFoodItemRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_market_proto_rawDescGZIP(), []int{7}
}

func (x *AddFoodItemRequest) GetItem() *FoodItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type AddFoodItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFoodItemResponse) Reset() {
	*x = AddFoodItemResponse{}
	mi := &file_protobuf_market_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFoodItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFoodItemResponse) ProtoMessage() {}

func (x *AddFoodItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_market_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFoodItemResponse.ProtoReflect.Descriptor instead.
func (*AddFoodItemResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_market_proto_rawDescGZIP(), []int{8}
}

func (x *AddFoodItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteFoodItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFoodItemRequest) Reset() {
	*x = DeleteFoodItemRequest{}
	mi := &file_protobuf_market_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFoodItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFoodItemRequest) ProtoMessage() {}

func (x *DeleteFoodItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_market_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFoodItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteFoodItemRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_market_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteFoodItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteFoodItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFoodItemResponse) Reset() {
	*x = DeleteFoodItemResponse{}
	mi := &file_protobuf_market_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFoodItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFoodItemResponse) ProtoMessage() {}

func (x *DeleteFoodItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_market_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFoodItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteFoodItemResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_market_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteFoodItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protobuf_market_proto protoreflect.FileDescriptor

const file_protobuf_market_proto_rawDesc = "" +
	"\n" +
	"\x15protobuf/market.proto\x12\x06market\"f\n" +
	"\bFoodItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\x1a\n" +
	"\bcalories\x18\x03 \x01(\x05R\bcalories\x12\x14\n" +
	"\x05sugar\x18\x04 \x01(\x02R\x05sugar\"\x19\n" +
	"\x17ListAllFoodItemsRequest\"B\n" +
	"\x18ListAllFoodItemsResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.market.FoodItemR\x05items\")\n" +
	"\x13ListFoodItemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"<\n" +
	"\x14ListFoodItemResponse\x12$\n" +
	"\x04item\x18\x01 \x01(\v2\x10.market.FoodItemR\x04item\"Q\n" +
	"\x15UpdateFoodItemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\x04item\x18\x02 \x01(\v2\x10.market.FoodItemR\x04item\"2\n" +
	"\x16UpdateFoodItemResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\":\n" +
	"\x12AddFoodItemRequest\x12$\n" +
	"\x04item\x18\x01 \x01(\v2\x10.market.FoodItemR\x04item\"/\n" +
	"\x13AddFoodItemResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"+\n" +
	"\x15DeleteFoodItemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"2\n" +
	"\x16DeleteFoodItemResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa5\x03\n" +
	"\rMarketService\x12W\n" +
	"\x10ListAllFoodItems\x12\x1f.market.ListAllFoodItemsRequest\x1a .market.ListAllFoodItemsResponse\"\x00\x12K\n" +
	"\fListFoodItem\x12\x1b.market.ListFoodItemRequest\x1a\x1c.market.ListFoodItemResponse\"\x00\x12Q\n" +
	"\x0eUpdateFoodItem\x12\x1d.market.UpdateFoodItemRequest\x1a\x1e.market.UpdateFoodItemResponse\"\x00\x12H\n" +
	"\vAddFoodItem\x12\x1a.market.AddFoodItemRequest\x1a\x1b.market.AddFoodItemResponse\"\x00\x12Q\n" +
	"\x0eDeleteFoodItem\x12\x1d.market.DeleteFoodItemRequest\x1a\x1e.market.DeleteFoodItemResponse\"\x00B\x0fZ\rrest/protobufb\x06proto3"

var (
	file_protobuf_market_proto_rawDescOnce sync.Once
	file_protobuf_market_proto_rawDescData []byte
)

func file_protobuf_market_proto_rawDescGZIP() []byte {
	file_protobuf_market_proto_rawDescOnce.Do(func() {
		file_protobuf_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_market_proto_rawDesc), len(file_protobuf_market_proto_rawDesc)))
	})
	return file_protobuf_market_proto_rawDescData
}

var file_protobuf_market_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_protobuf_market_proto_goTypes = []any{
	(*FoodItem)(nil),                 // 0: market.FoodItem
	(*ListAllFoodItemsRequest)(nil),  // 1: market.ListAllFoodItemsRequest
	(*ListAllFoodItemsResponse)(nil), // 2: market.ListAllFoodItemsResponse
	(*ListFoodItemRequest)(nil),      // 3: market.ListFoodItemRequest
	(*ListFoodItemResponse)(nil),     // 4: market.ListFoodItemResponse
	(*UpdateFoodItemRequest)(nil),    // 5: market.UpdateFoodItemRequest
	(*UpdateFoodItemResponse)(nil),   // 6: market.UpdateFoodItemResponse
	(*AddFoodItemRequest)(nil),       // 7: market.AddFoodItemRequest
	(*AddFoodItemResponse)(nil),      // 8: market.AddFoodItemResponse
	(*DeleteFoodItemRequest)(nil),    // 9: market.DeleteFoodItemRequest
	(*DeleteFoodItemResponse)(nil),   // 10: market.DeleteFoodItemResponse
}
var file_protobuf_market_proto_depIdxs = []int32{
	0,  // 0: market.ListAllFoodItemsResponse.items:type_name -> market.FoodItem
	0,  // 1: market.ListFoodItemResponse.item:type_name -> market.FoodItem
	0,  // 2: market.UpdateFoodItemRequest.item:type_name -> market.FoodItem
	0,  // 3: market.AddFoodItemRequest.item:type_name -> market.FoodItem
	1,  // 4: market.MarketService.ListAllFoodItems:input_type -> market.ListAllFoodItemsRequest
	3,  // 5: market.MarketService.ListFoodItem:input_type -> market.ListFoodItemRequest
	5,  // 6: market.MarketService.UpdateFoodItem:input_type -> market.UpdateFoodItemRequest
	7,  // 7: market.MarketService.AddFoodItem:input_type -> market.AddFoodItemRequest
	9,  // 8: market.MarketService.DeleteFoodItem:input_type -> market.DeleteFoodItemRequest
	2,  // 9: market.MarketService.ListAllFoodItems:output_type -> market.ListAllFoodItemsResponse
	4,  // 10: market.MarketService.ListFoodItem:output_type -> market.ListFoodItemResponse
	6,  // 11: market.MarketService.UpdateFoodItem:output_type -> market.UpdateFoodItemResponse
	8,  // 12: market.MarketService.AddFoodItem:output_type -> market.AddFoodItemResponse
	10, // 13: market.MarketService.DeleteFoodItem:output_type -> market.DeleteFoodItemResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_protobuf_market_proto_init() }
func file_protobuf_market_proto_init() {
	if File_protobuf_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_market_proto_rawDesc), len(file_protobuf_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_market_proto_goTypes,
		DependencyIndexes: file_protobuf_market_proto_depIdxs,
		MessageInfos:      file_protobuf_market_proto_msgTypes,
	}.Build()
	File_protobuf_market_proto = out.File
	file_protobuf_market_proto_goTypes = nil
	file_protobuf_market_proto_depIdxs = nil
}
