// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: protobuf/market.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketService_ListAllFoodItems_FullMethodName = "/market.MarketService/ListAllFoodItems"
	MarketService_ListFoodItem_FullMethodName     = "/market.MarketService/ListFoodItem"
	MarketService_UpdateFoodItem_FullMethodName   = "/market.MarketService/UpdateFoodItem"
	MarketService_AddFoodItem_FullMethodName      = "/market.MarketService/AddFoodItem"
	MarketService_DeleteFoodItem_FullMethodName   = "/market.MarketService/DeleteFoodItem"
)

// MarketServiceClient is the client API for MarketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketServiceClient interface {
	ListAllFoodItems(ctx context.Context, in *ListAllFoodItemsRequest, opts ...grpc.CallOption) (*ListAllFoodItemsResponse, error)
	ListFoodItem(ctx context.Context, in *ListFoodItemRequest, opts ...grpc.CallOption) (*ListFoodItemResponse, error)
	UpdateFoodItem(ctx context.Context, in *UpdateFoodItemRequest, opts ...grpc.CallOption) (*UpdateFoodItemResponse, error)
	AddFoodItem(ctx context.Context, in *AddFoodItemRequest, opts ...grpc.CallOption) (*AddFoodItemResponse, error)
	DeleteFoodItem(ctx context.Context, in *DeleteFoodItemRequest, opts ...grpc.CallOption) (*DeleteFoodItemResponse, error)
}

type marketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketServiceClient(cc grpc.ClientConnInterface) MarketServiceClient {
	return &marketServiceClient{cc}
}

func (c *marketServiceClient) ListAllFoodItems(ctx context.Context, in *ListAllFoodItemsRequest, opts ...grpc.CallOption) (*ListAllFoodItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllFoodItemsResponse)
	err := c.cc.Invoke(ctx, MarketService_ListAllFoodItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) ListFoodItem(ctx context.Context, in *ListFoodItemRequest, opts ...grpc.CallOption) (*ListFoodItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFoodItemResponse)
	err := c.cc.Invoke(ctx, MarketService_ListFoodItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) UpdateFoodItem(ctx context.Context, in *UpdateFoodItemRequest, opts ...grpc.CallOption) (*UpdateFoodItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFoodItemResponse)
	err := c.cc.Invoke(ctx, MarketService_UpdateFoodItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) AddFoodItem(ctx context.Context, in *AddFoodItemRequest, opts ...grpc.CallOption) (*AddFoodItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddFoodItemResponse)
	err := c.cc.Invoke(ctx, MarketService_AddFoodItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) DeleteFoodItem(ctx context.Context, in *DeleteFoodItemRequest, opts ...grpc.CallOption) (*DeleteFoodItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFoodItemResponse)
	err := c.cc.Invoke(ctx, MarketService_DeleteFoodItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServiceServer is the server API for MarketService service.
// All implementations must embed UnimplementedMarketServiceServer
// for forward compatibility.
type MarketServiceServer interface {
	ListAllFoodItems(context.Context, *ListAllFoodItemsRequest) (*ListAllFoodItemsResponse, error)
	ListFoodItem(context.Context, *ListFoodItemRequest) (*ListFoodItemResponse, error)
	UpdateFoodItem(context.Context, *UpdateFoodItemRequest) (*UpdateFoodItemResponse, error)
	AddFoodItem(context.Context, *AddFoodItemRequest) (*AddFoodItemResponse, error)
	DeleteFoodItem(context.Context, *DeleteFoodItemRequest) (*DeleteFoodItemResponse, error)
	mustEmbedUnimplementedMarketServiceServer()
}

// UnimplementedMarketServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketServiceServer struct{}

func (UnimplementedMarketServiceServer) ListAllFoodItems(context.Context, *ListAllFoodItemsRequest) (*ListAllFoodItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllFoodItems not implemented")
}
func (UnimplementedMarketServiceServer) ListFoodItem(context.Context, *ListFoodItemRequest) (*ListFoodItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFoodItem not implemented")
}
func (UnimplementedMarketServiceServer) UpdateFoodItem(context.Context, *UpdateFoodItemRequest) (*UpdateFoodItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFoodItem not implemented")
}
func (UnimplementedMarketServiceServer) AddFoodItem(context.Context, *AddFoodItemRequest) (*AddFoodItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddFoodItem not implemented")
}
func (UnimplementedMarketServiceServer) DeleteFoodItem(context.Context, *DeleteFoodItemRequest) (*DeleteFoodItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFoodItem not implemented")
}
func (UnimplementedMarketServiceServer) mustEmbedUnimplementedMarketServiceServer() {}
func (UnimplementedMarketServiceServer) testEmbeddedByValue()                       {}

// UnsafeMarketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketServiceServer will
// result in compilation errors.
type UnsafeMarketServiceServer interface {
	mustEmbedUnimplementedMarketServiceServer()
}

func RegisterMarketServiceServer(s grpc.ServiceRegistrar, srv MarketServiceServer) {
	// If the following call panics, it indicates UnimplementedMarketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketService_ServiceDesc, srv)
}

func _MarketService_ListAllFoodItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllFoodItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).ListAllFoodItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_ListAllFoodItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).ListAllFoodItems(ctx, req.(*ListAllFoodItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_ListFoodItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFoodItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).ListFoodItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_ListFoodItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).ListFoodItem(ctx, req.(*ListFoodItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_UpdateFoodItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFoodItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).UpdateFoodItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_UpdateFoodItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).UpdateFoodItem(ctx, req.(*UpdateFoodItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_AddFoodItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFoodItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).AddFoodItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_AddFoodItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).AddFoodItem(ctx, req.(*AddFoodItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_DeleteFoodItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFoodItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).DeleteFoodItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_DeleteFoodItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).DeleteFoodItem(ctx, req.(*DeleteFoodItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketService_ServiceDesc is the grpc.ServiceDesc for MarketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "market.MarketService",
	HandlerType: (*MarketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAllFoodItems",
			Handler:    _MarketService_ListAllFoodItems_Handler,
		},
		{
			MethodName: "ListFoodItem",
			Handler:    _MarketService_ListFoodItem_Handler,
		},
		{
			MethodName: "UpdateFoodItem",
			Handler:    _MarketService_UpdateFoodItem_Handler,
		},
		{
			MethodName: "AddFoodItem",
			Handler:    _MarketService_AddFoodItem_Handler,
		},
		{
			MethodName: "DeleteFoodItem",
			Handler:    _MarketService_DeleteFoodItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/market.proto",
}
